language: cpp

group: stable

git:
  depth: 1

sudo: false

jobs:
  - os: linux
    arch: amd64

    before_script:
      - mkdir Build
      - cd Build
      - cmake -D ENABLE_COVERAGE:BOOL=TRUE ..
    script:
      - cmake --build .
      - ctest
      - bash <(curl -s https://codecov.io/bash)

  - os: linux
    arch: amd64

    before_script:
      - mkdir Build
      - cd Build
      - cmake -D ENABLE_AVX2=1 ..
    script:
      - cmake --build .
      - ctest

  - os: linux
    arch: amd64

    before_script:
      - mkdir Build
      - cd Build
      - cmake -D ENABLE_SSE2=1 ..
    script:
      - cmake --build .
      - ctest

  - os: linux
    arch: arm64
    virt: lxd

    before_script:
      - mkdir Build
      - cd Build
      - cmake ..
    script:
      - cmake --build .
      - ctest

  - os: linux
    arch: arm64-graviton2
    dist: focal
    virt: vm
    compiler: clang++

    before_script:
      - mkdir ./Build
      - clang++ -g -O0 -Wall ./Tests/Test.cpp -std=c++11 -I ./Include -o ./Build/QTest.bin
    script:
      - ./Build/QTest.bin

  - os: osx

    before_script:
      - mkdir ./Build
      - g++ -g -O0 -Wall ./Tests/Test.cpp -std=c++11 -I ./Include -o ./Build/QTest.bin
    script:
      - ./Build/QTest.bin

  - os: linux
    arch: ppc64le
    group: edge

    before_script:
      - mkdir ./Build
      - g++ -g -O0 -Wall ./Tests/Test.cpp -std=c++11 -I ./Include -o ./Build/QTest.bin
    script:
      - ./Build/QTest.bin

  - os: linux
    arch: s390x
    group: edge

    before_script:
      - mkdir ./Build
      - g++ -g -O0 -Wall ./Tests/Test.cpp -std=c++11 -I ./Include -o ./Build/QTest.bin
    script:
      - ./Build/QTest.bin
